\addvspace {10\p@ }
\contentsline {figure}{\numberline {1.1}{\ignorespaces An illustration of two acoustic emplacements. The left rig consists of a float (orange circle) capable of lifting the rig without the ballast, a long rope, an acoustic receiver (green cylinder) and an acoustic quick release (red) attached to a strong ballast (purple). The ballast is sufficiently heavy to keep the entire rig from drifting with the current. Upon signaling the quick release, the ballast is released, and the float carries the rig (receiver, line, and quick release) to the surface. This type of rig is suitable for deeper deployments, or areas where no solid structure exists (coral, rock formation). The right rig consists of an emplacement for shallower waters or near solid structures (coral, rock formation). Here, a steel rod is driven into a solid structure, cemented into place, and an acoustic receiver is attached. \relax }}{2}{figure.caption.6}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {2.1}{\ignorespaces An illustration of how ray tracing is used within a 3D environment to identify potential visual obstructions. Ray tracing is used to determine which cells potentially block the line of sight between the receiver-containing cell $p$ and the target cell $q$. Shaded cells must be evaluated by a Line of Sight algorithm to determine which portion of the target area in $q$ is visible from $p$. \cite {Akbarzadeh2013}\relax }}{13}{figure.caption.12}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {3.1}{\ignorespaces (a) illustrates the bathymetric shadowing model for two adjacent cells within a bathymetric grid. (b) shows how artificially increasing the resolution of the bathymetric grid from (a) using the duplication method of cell sub-division does not affect the bathymetric shadowing model but increases the number of cells to consider. (c) shows how artificially increasing the resolution using a smoothing function increased the number of cells to consider and can lead to inflated signal reception.\relax }}{20}{figure.caption.13}
\contentsline {figure}{\numberline {3.2}{\ignorespaces An example of a distribution given by the Ornstein-Uhlenbeck Model with a high attraction value in the x-direction, a low attraction value in the y-direction, and a correlation value of 0.7.\relax }}{22}{figure.caption.14}
\contentsline {figure}{\numberline {3.3}{\ignorespaces An illustration of how ray tracing and integration over a shape function can be used in Option 2 \& Option 3 to compute the probability of detecting fish within a cell. Dotted lines indicate the maximum and minimum depths visible to the receiver. The normal distributions in green/red indicate the distribution of fish within a given cell as determined by a shape function. The green portion of the curve indicates the observable section of the distribution, while the red indicates the unobservable section. The observable section (green) is computed by integration over the shape function. \relax }}{26}{figure.caption.15}
\contentsline {figure}{\numberline {3.4}{\ignorespaces An illustration of how the critical slope, and $D_{max}$ are computed between cells $p$ and $q$. The slope between the receiver and all intervening cells are computed (blue and red arrows). Then, the greatest slope is selected as $m_{crit}$ (dark red arrow) because it poses the greatest obstruction to vision of cell $q$. Finally, $m_{crit}$ is projected into cell $q$ (the light red arrow) to determine $D_{max}$. \relax }}{27}{figure.caption.16}
\contentsline {figure}{\numberline {3.5}{\ignorespaces An illustration of the Exact Suppression Algorithm. (a) depicts a bathymetry grid with infinitely high walls (the white 'h' shape) on an otherwise flat plane (blue region). (b) depicts a Behavior Grid with a distribution (given by the OU movement model) of animals around the walls. (c) shows the computed Goodness of Receiver (receiver) locations within the study site. The program first identifies location 1 (the blue circle) as having the highest unique data recovery rate, and places a receiver there. The dotted lines represent the receiver's Detection Range. In (d), the program suppresses the Behavior Grid by subtracting the ERT of each cell within Suppression Range. Here the Suppression Range Factor is 1.0, so the Suppression Area is the same as the Detection Area. In (e), the Goodness Grid is recalculated, taking into account the suppressed Behavior Grid. Additionally, the program identifies location 2 as having the highest Unique Data Recovery Rate. In (f), the Behavior Grid is again suppressed to account for the placement of receiver (2). \relax }}{29}{figure.caption.17}
\contentsline {figure}{\numberline {3.6}{\ignorespaces An illustration of how ray tracing is used within a 3D environment to identify potential visual obstructions. Ray tracing is used to determine which cells potentially block the line of sight between the receiver-containing cell $p$, and the target cell $q$. Shaded cells must be evaluated by the Line of Sight algorithm to determine which portion of the water column in $q$ that is visible from $p$. \cite {Akbarzadeh2013}\relax }}{32}{figure.caption.18}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {4.1}{\ignorespaces A screen shot of the webapp GUI. On the right is a Google Map widget that assists users in choosing latitude and longitude boundaries for their study site (defining their Bathymetry Grid). On the left is a list of simulation options implemented as drop-down lists, and simulation parameters implemented as text boxes. At the bottom (hidden) is a ``Submit'' button that sends that validates the parameters and sends them to the server. All parameters fields and lists display ``tool tip'' style descriptions of the parameter that field/list represents. \relax }}{43}{figure.caption.23}
\addvspace {10\p@ }
\contentsline {figure}{\numberline {5.1}{\ignorespaces A graphical representation of the cumulative and per-receiver UDRR. User-placed receivers are representd by a grey line, system-placed receivers are represented by the black line, and projected receivers are represented by the green line.\relax }}{47}{figure.caption.24}
\contentsline {figure}{\numberline {5.2}{\ignorespaces A graphical representation of an artificial Bathymetry file at a 1m resolution (each cell has an edge length of 1m). Darker cells represent greater depths, while white cells represent inaccessible terrain (dry land). The optimal receiver locations are shown on the Grid as blue numbered circles, user-placed receivers as grey circles, and projected receivers as green circles. All receivers have their Detection Range shown as dotted lines.\relax }}{48}{figure.caption.25}
\contentsline {figure}{\numberline {5.3}{\ignorespaces The Behavior Grid represented as a heat map Higher levels of animal residency correspond with pink cells, moderate levels as light blue, and white for non-residency (inhospitable habitat such as dry land). The optimal receiver locations are shown on the Grid as blue numbered circles, user-placed receivers as grey circles, and projected receivers as green circles. All receivers have their Detection Range shown as dotted lines.\relax }}{49}{figure.caption.26}
\contentsline {figure}{\numberline {5.4}{\ignorespaces The Goodness Grid represented as a heat map showing the sum total of Estimated Receivable Transmissions (ERT) for a receiver placed in a particular cell. The legend in the top right assigns color coding to various ERT values. The optimal receiver locations are shown on the Grid as blue numbered circles, user-placed receivers as grey circles, and projected receivers as green circles. All receivers have their Detection Range shown as dotted lines.\relax }}{50}{figure.caption.27}
\contentsline {figure}{\numberline {5.5}{\ignorespaces The Coverage Grid represented as a heatmap showing the quantity of Estimated Receivable Transmissions from each cell in the study site, for the designated receiver array configuration. The legend in the top right assigns color coding to various ERT values. The optimal receiver locations are shown on the Grid as blue numbered circles, user-placed receivers as grey circles, and projected receivers as green circles. All receivers have their Detection Range shown as dotted lines. The missing corner of of Receiver 4's Detection Area is due to the presence of an obscuring section of Bathymetry (dry land).\relax }}{51}{figure.caption.28}
\contentsline {figure}{\numberline {5.6}{\ignorespaces A first-person view of the 3D space modeled in the program. Users would be able to ``swim'' through the environment and gain a better perspective on what they are modeling, what their receiver array might look like in the environment, and where more receivers might be needed.\relax }}{54}{figure.caption.29}
\addvspace {10\p@ }
\addvspace {10\p@ }
